
package org;

import java.awt.Color;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.border.Border;

/** Author Brian King **/

public class JNotesFrame extends JFrame 
{
    Font myFont = new Font ("Times New Roman", Font.PLAIN, 22);
    Border blackline = BorderFactory.createLineBorder(Color.black);
    
    String programNotes = "This program tracks Covid-19 statistics in the U.S. from March 1st, 2020 through the most recent complete month."
            + " Data is stored and retrieved from a MySql database I created. New entries must follow the most recent date added to the database."
            + " A User can delete a specific date, but only one date can be deleted at a time and the User must repopulate it with data"
            + "before closing the program. \n\n"
            + "The User selects which month of data to view from ComboBoxes. The ComboBoxes are coded to automatically update with the most recent"
            + " complete month; however, a programmer must code the ComputeMonthlyAvgTotalCases class with the most recent complete month to prevent a"
            + " runtime error when the most recent month tries to access its data. \n\n"
            + "In the Chart panel where a User can select various categories to chart, the start and end date must not exceed 365 days."
            + " And if the User selects more than 30 days to view, not all dates will be eligible along the X-Axis. \n\n"
            + " Data can be viewed by sequential months or by selecting timeframes.";
            
    public JNotesFrame() 
    {
        initComponents();
        setLocationRelativeTo(this);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        // set color of text to teal
        JNotesTA.setForeground(new Color(0, 128 ,128));
        JNotesTA.setFont(myFont);
        // add padding to text in TextArea
        JNotesTA.setBorder(BorderFactory.createCompoundBorder(blackline, 
                           BorderFactory.createEmptyBorder(20, 20, 20, 20)));
        // TextArea will not be edited
        JNotesTA.setEditable(false);
        JNotesTA.setLineWrap(true);
        JNotesTA.setWrapStyleWord(true);
        // add String programNotes text
        JNotesTA.setText(programNotes);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JNotesPagePnl = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JNotesTA = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JNotesPagePnl.setBackground(new java.awt.Color(102, 102, 102));

        JNotesTA.setColumns(20);
        JNotesTA.setRows(5);
        jScrollPane1.setViewportView(JNotesTA);

        javax.swing.GroupLayout JNotesPagePnlLayout = new javax.swing.GroupLayout(JNotesPagePnl);
        JNotesPagePnl.setLayout(JNotesPagePnlLayout);
        JNotesPagePnlLayout.setHorizontalGroup(
            JNotesPagePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JNotesPagePnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1006, Short.MAX_VALUE)
                .addContainerGap())
        );
        JNotesPagePnlLayout.setVerticalGroup(
            JNotesPagePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JNotesPagePnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JNotesPagePnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JNotesPagePnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JNotesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JNotesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JNotesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JNotesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JNotesFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JNotesPagePnl;
    private javax.swing.JTextArea JNotesTA;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
